local spec = require('cmp.utils.spec')

local context = require('cmp.context')

describe('context', function()
  before_each(spec.before)

  describe('new' , function()
    it('middle of text', function()
      vim.fn.setline('1', 'function! s:name() abort')
      vim.bo.filetype = 'vim'
      vim.fn.execute('normal! fm')
      local ctx = context.new()
      assert.are.equal(ctx.filetype, 'vim')
      assert.are.equal(ctx.cursor.row, 1)
      assert.are.equal(ctx.cursor.col, 15)
      assert.are.equal(ctx.cursor_line, 'function! s:name() abort')
      assert.are.equal(ctx.offset, 13)
      assert.are.equal(ctx.offset_before_line, 'function! s:')
      assert.are.equal(ctx.input, 'na')
      assert.are.equal(ctx.insert_range.start.col, 13)
      assert.are.equal(ctx.insert_range['end'].col, 15)
      assert.are.equal(ctx.replace_range.start.col, 13)
      assert.are.equal(ctx.replace_range['end'].col, 17)
    end)

    it('tab indent', function()
      vim.fn.setline('1', '\t\tab')
      vim.bo.filetype = 'vim'
      vim.fn.execute('normal! fb')
      local ctx = context.new()
      assert.are.equal(ctx.filetype, 'vim')
      assert.are.equal(ctx.cursor.row, 1)
      assert.are.equal(ctx.cursor.col, 4)
      assert.are.equal(ctx.cursor_line, '\t\tab')
      assert.are.equal(ctx.offset, 3)
      assert.are.equal(ctx.offset_before_line, '\t\t')
      assert.are.equal(ctx.input, 'a')
      assert.are.equal(ctx.insert_range.start.col, 3)
      assert.are.equal(ctx.insert_range['end'].col, 4)
      assert.are.equal(ctx.replace_range.start.col, 3)
      assert.are.equal(ctx.replace_range['end'].col, 5)
    end)
  end)
end)
