local spec = require('cmp.utils.spec')
local keymap = require('cmp.utils.keymap')
local Keymap = require('cmp.kit.Vim.Keymap')
local Async = require('cmp.kit.Async')
local api = require('cmp.utils.api')

describe('api', function()
  before_each(spec.before)
  describe('get_cursor', function()
    it('insert-mode', function()
      Keymap.spec(Async.async(function()
        Keymap.send(keymap.t('i\t1234567890'), 'n'):await()
        assert.are.equal(api.get_cursor()[2], 11)
      end))
    end)
    it('cmdline-mode', function()
      Keymap.spec(Async.async(function()
        Keymap.send(keymap.t(':\t1234567890'), 'n'):await()
        assert.are.equal(api.get_cursor()[2], 11)
      end))
    end)
  end)

  describe('get_screen_cursor', function()
    it('insert-mode', function()
      Keymap.spec(Async.async(function()
        Keymap.send(keymap.t('iあいうえお'), 'n'):await()
        assert.are.equal(api.get_screen_cursor()[2], 10)
      end))
    end)
    it('cmdline-mode', function()
      Keymap.spec(Async.async(function()
        Keymap.send(keymap.t(':あいうえお'), 'n'):await()
        assert.are.equal(10, api.get_screen_cursor()[2])
      end))
    end)
  end)

  describe('get_cursor_before_line', function()
    it('insert-mode', function()
      Keymap.spec(Async.async(function()
        Keymap.send(keymap.t('i\t1234567890<Left><Left>'), 'n'):await()
        assert.are.same(api.get_cursor_before_line(), '\t12345678')
      end))
    end)
    it('cmdline-mode', function()
      Keymap.spec(Async.async(function()
        Keymap.send(keymap.t(':\t1234567890<Left><Left>'), 'n'):await()
        assert.are.same(api.get_cursor_before_line(), '\t12345678')
      end))
    end)
  end)
end)
