local str = require('cmp.utils.str')

describe('utils.str', function()
  it('get_word', function()
    assert.are.equal(str.get_word('print'), 'print')
    assert.are.equal(str.get_word('$variable'), '$variable')
    assert.are.equal(str.get_word('print()'), 'print')
    assert.are.equal(str.get_word('["cmp#confirm"]'), '["cmp#confirm"]')
    assert.are.equal(str.get_word('"devDependencies":', string.byte('"')), '"devDependencies')
    assert.are.equal(str.get_word('"devDependencies": ${1},', string.byte('"')), '"devDependencies')
    assert.are.equal(str.get_word('#[cfg(test)]'), '#[cfg(test)]')
    assert.are.equal(str.get_word('import { GetStaticProps$1 } from "next";', nil, 9), 'import { GetStaticProps')
    assert.are.equal(str.get_word('do {\n${1:statements}\n}while ($0)', nil, 0), 'do')
    assert.are.equal(str.get_word('do {\n${1:statements}\n}while ($0)', nil, 1), 'do')
    assert.are.equal(str.get_word('do {\n${1:statements}\n}while ($0)', nil, 2), 'do')
    assert.are.equal(str.get_word('for (${1:init-statement}; ${2:condition}; ${3:inc-expression}) {\n$0\n}', nil, 0), 'for')
    assert.are.equal(str.get_word('for (${1:init-statement}; ${2:condition}; ${3:inc-expression}) {\n$0\n}', nil, 1), 'for')
    assert.are.equal(str.get_word('for (${1:init-statement}; ${2:condition}; ${3:inc-expression}) {\n$0\n}', nil, 2), 'for')
    assert.are.equal(str.get_word('for (${1:init-statement}; ${2:condition}; ${3:inc-expression}) {\n$0\n}', nil, 3), 'for')
  end)

  it('remove_suffix', function()
    assert.are.equal(str.remove_suffix('log()', '$0'), 'log()')
    assert.are.equal(str.remove_suffix('log()$0', '$0'), 'log()')
    assert.are.equal(str.remove_suffix('log()${0}', '${0}'), 'log()')
    assert.are.equal(str.remove_suffix('log()${0:placeholder}', '${0}'), 'log()${0:placeholder}')
  end)

  it('escape', function()
    assert.are.equal(str.escape('plain', {}), 'plain')
    assert.are.equal(str.escape('plain\\', {}), 'plain\\\\')
    assert.are.equal(str.escape('plain\\"', {}), 'plain\\\\"')
    assert.are.equal(str.escape('pla"in', { '"' }), 'pla\\"in')
    assert.are.equal(str.escape('call("")', { '"' }), 'call(\\"\\")')
  end)
end)
