name: Bug Report
description: Report a problem in nvim-cmp
labels: [bug]
body:
  - type: checkboxes
    id: faq-prerequisite
    attributes:
      label: FAQ
      options:
        - label: I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt) and it didn't resolve my problem.
          required: true

  - type: checkboxes
    id: announcement-prerequisite
    attributes:
      label: Announcement
      options:
        - label: I have checked [Breaking change announcement](https://github.com/hrsh7th/nvim-cmp/issues/231).
          required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce using the minimal config provided below."
      placeholder: |
        1. `nvim -u minimal_init.lua`
        2. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Minimal config"
      render: Lua
      description: |
        you can download a minimal_init.lua template via `curl -fLO https://raw.githubusercontent.com/hrsh7th/nvim-cmp/main/utils/minimal_init.lua`
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Description"
      description: "Describe in detail what happens"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Full reproduction steps. Include a sample file if your issue relates to a specific filetype."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A description of the behavior you expected."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "A description of the actual behavior."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Additional context"
      description: "Any other relevant information"
